apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-learning
  namespace: brightflow-ml
  labels:
    app: brightflow-ml
    component: ml-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brightflow-ml
      component: ml-learning
  template:
    metadata:
      labels:
        app: brightflow-ml
        component: ml-learning
    spec:
      containers:
        - name: ml-learning
          image: python:3.9-slim
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args:
            - -c
            - |
              # Install dependencies
              pip install requests pandas numpy

              # Copy application code
              cp /app/ml_learning_system.py /tmp/

              # Run the ML learning system
              cd /tmp
              python ml_learning_system.py

              # Keep container running for logs
              tail -f /dev/null
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: brightflow-secrets
                  key: github-token
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: data-volume
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "test -f /tmp/ml_learning_complete || echo 'running'"
            initialDelaySeconds: 60
            periodSeconds: 120
      volumes:
        - name: app-code
          configMap:
            name: brightflow-app-code
        - name: data-volume
          persistentVolumeClaim:
            claimName: brightflow-data-pvc
      restartPolicy: Always
