apiVersion: batch/v1
kind: CronJob
metadata:
  name: site-data-reader-cronjob
  namespace: brightflow-ml
  labels:
    app: brightflow-ml
    component: site-data-reader
spec:
  # Run every 30 minutes
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: brightflow-ml
            component: site-data-reader
        spec:
          containers:
          - name: site-data-reader
            image: python:3.9-slim
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash"]
            args:
              - -c
              - |
                # Install dependencies
                pip install requests pandas numpy scikit-learn
                
                # Copy application code
                cp /app/site_data_reader.py /tmp/
                
                # Run the site data reader
                cd /tmp
                python site_data_reader.py
            env:
            - name: PYTHONUNBUFFERED
              value: "1"
            volumeMounts:
            - name: app-code
              mountPath: /app
            - name: data-volume
              mountPath: /data
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: app-code
            configMap:
              name: brightflow-app-code
          - name: data-volume
            persistentVolumeClaim:
              claimName: brightflow-data-pvc
          restartPolicy: OnFailure
